name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.YOUR_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan 13.126.119.82 >> ~/.ssh/known_hosts

    - name: SSH into EC2 and install prerequisites
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@ec2-13-126-119-82.ap-south-1.compute.amazonaws.com 'sudo yum update && sudo yum install -y nodejs && node -v && npm -v && sudo yum install -y git'

    - name: Create 'app' directory on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@ec2-13-126-119-82.ap-south-1.compute.amazonaws.com 'mkdir -p ~/app'    

    - name: Git init
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@ec2-13-126-119-82.ap-south-1.compute.amazonaws.com 'cd ~/app && git init' 

    - name: Debug - List Repository Contents
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@ec2-13-126-119-82.ap-south-1.compute.amazonaws.com 'cd ~/app && ls -la ~/app'
   
    # - name: Git remote add oringin URL
    #   run: |
    #     ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@ec2-13-126-119-82.ap-south-1.compute.amazonaws.com 'cd ~/app && git remote add -f origin https://github.com/counain/deploy-automation.git'

    - name: Git Pull Origin Master
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@ec2-13-126-119-82.ap-south-1.compute.amazonaws.com 'cd ~/app && git pull origin master'
 
    
    - name: npm install express && npm init && node app.js
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@ec2-13-126-119-82.ap-south-1.compute.amazonaws.com 'cd ~/app && npm install && npm install express && npm init && node app.js'